name: glass_keep
description: Glassmorphism Google Keep clone as PWA
publish_to: 'none'
version: 1.1.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  intl: ^0.20.2
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.1
  flutter_staggered_grid_view: ^0.7.0
  cupertino_icons: ^1.0.8
  window_manager: ^0.4.3
  fast_noise: ^2.0.0
  sensors_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  shaders:
    - shaders/chromatic_aberration.frag
    - shaders/film_grain.frag
