{
  "format_version": 1,
  "sksl": {
    "entrypoint": "film_grain_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform float uTime;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nfloat FLT_flutter_local_random(vec2 uv)\n{\n    return fract(sin(dot(uv, vec2(12.98980045318603515625, 78.233001708984375))) * 43758.546875);\n}\n\nvoid FLT_main()\n{\n    vec2 uv_1 = FLT_flutter_local_FlutterFragCoord() / uSize;\n    vec2 param = uv_1 + vec2(fract(uTime));\n    float noise = FLT_flutter_local_random(param);\n    fragColor = vec4(1.0, 1.0, 1.0, noise * 0.039999999105930328369140625);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uTime",
        "rows": 1,
        "type": 10
      }
    ]
  }
}